name: Deploy to AWS Pipeline

concurrency: deploy

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-to-aws.yaml
    secrets: inherit
    with:
      stack-suffix: dev
      targetEnv: 'dev'