name: Deploy to AWS

concurrency: pr-build-${{ github.event.pull_request.number }}

on:
  workflow_call:
    inputs:
      stack-suffix:
        description: A string to append to the app's stack names. Intended for use with deploying stacks to the same account for PR app purposes.
        required: false
        type: string
      targetEnv:
        description: Determines where to look for the Backend API URL
        required: true
        type: string

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: geobrawl-frontend-${{ inputs.stack-suffix }}
          template: serverless.yaml
          no-fail-on-empty-changeset: '1'
          parameter-overrides: "Name=geobrawl-frontend-${{ inputs.stack-suffix }}"
      - name: Install dependencies
        run: yarn install
      - name: Set config file
        run:  yarn run setconfig dev
      - name: Build App
        run: API_BASE_URL=api-test yarn run build
        env:
          CI: false
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
      - name: Deploy To S3
        run: aws s3 sync ./build s3://geobrawl-frontend-${{ inputs.stack-suffix }}
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: /*
          AWS_REGION: us-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}